version: '3.8'

services:
  # MySQL Database Service
  db:
    image: mysql:8.2
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
      MYSQL_USER: user        
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Express Backend Service
  backend:
    build: ./backend
    container_name: express_backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: myapp
    depends_on:
      db:
        condition: service_healthy
    restart: always

  # React Frontend Service
  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5001/api/auth
    depends_on:
      - backend
    restart: always

volumes:
  db_data: